version: '3.8'

services:
  backend:
    image: openjdk:14-slim
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend:/backend:cached
    working_dir: /backend

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: pyonkichi
      MYSQL_USER: pyonkichi_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: