version: '3.8'

services:
  backend:
    image: openjdk:14-slim
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./backend:/backend:cached
    working_dir: /backend

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: crafts
      MYSQL_USER: crafts_admin
      MYSQL_PASSWORD: Br2scw2D0THdvKzp
      MYSQL_ROOT_PASSWORD: Br2scw2D0THdvKzp
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: